/*
 * File:           FuzzyTaskHandler.java
 * Date:           22. Juni 2010  17:21
 *
 * @author  malygos
 * @version generated by NetBeans XML module
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package tasks.xml;

import org.xml.sax.Attributes;
import org.xml.sax.ContentHandler;
import org.xml.sax.SAXException;

/**
 *
 * @author malygos
 */
public interface FuzzyTaskHandler extends ContentHandler {

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_jobs(final Attributes meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_jobs() throws SAXException;

    /**
     *
     * An empty element event handling method.
     * @param data value or null
     */
    public void handle_connection(final Attributes meta) throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_task(final Attributes meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_task() throws SAXException;

    /**
     *
     * An empty element event handling method.
     * @param data value or null
     */
    public void handle_job(final Attributes meta) throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_rules(final Attributes meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_rules() throws SAXException;

    /**
     *
     * An empty element event handling method.
     * @param data value or null
     */
    public void handle_size(final Attributes meta) throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_variables(final Attributes meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_variables() throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_function(final Attributes meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_function() throws SAXException;

    /**
     *
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_id(final String data, final Attributes meta) throws SAXException;

    /**
     *
     * An empty element event handling method.
     * @param data value or null
     */
    public void handle_point(final Attributes meta) throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_graph(final Attributes meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_graph() throws SAXException;

    /**
     *
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_name(final String data, final Attributes meta) throws SAXException;

    /**
     *
     * An empty element event handling method.
     * @param data value or null
     */
    public void handle_rule(final Attributes meta) throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_part(final Attributes meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_part() throws SAXException;

    /**
     *
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_variable(final Attributes meta) throws SAXException;

    /**
     *
     * A container element end event handling method.
     */
    public void end_variable() throws SAXException;

}
